navbar:
  logo: 
    img: 
    icon: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    title: ibuyu
  menu:
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
  search: 搜索   
favicon:
  small: /images/f72b700201cf47b88812536961f2c9a6.jpg
  medium: /images/f72b700201cf47b88812536961f2c9a6.jpg

sidebar:
  widget_library:
    blogger:
      class: blogger
      avatar: https://p1.music.126.net/k2SCE495sR-iDDeQQ_uDww==/18585045044586994.jpg?param=60y50
      subtitle: 一个帅气的打工人
      social:
        - icon: 
          url: atom.xml
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/020-rss.svg
        - icon: 
          url: mailto:849852463@qq.com
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/045-telegram.svg
        - icon: 
          url: https://github.com/lixiangyong
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/029-github.svg
        - icon: 
          url: https://music.163.com/#/user/home?id=36554425
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/006-youtube.svg

site_footer:
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:849852463@qq.com
    - icon: fab fa-github
      url: https://github.com/lixiangyong
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=36554425
  copyright: '[Copyright © 2017-2020 lixiangyong](www.ibuyu.today)'

search:
    enable: true
    service: hexo  # hexo, google, algolia, azure, baidu
    js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2.6.4/js/search.js
    google:
      apiKey:
      engineId:
    algolia:
      applicationID:
      apiKey:
      indexName:
    azure:
      serviceName:
      indexName:
      queryKey:
    baidu:
      apiId:

cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: 'ibuyu'
  subtitle: ''
  search: A Wonderful Theme for Hexo # search bar placeholder
  features:
    - name: 文档
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: /v4/getting-started/
    - name: 帮助
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
      url: faqs/
    - name: 示例
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f396.svg
      url: /examples/
    - name: 社区
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
      url: /contributors/
    - name: 博客
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 源码
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/volantis-x/hexo-theme-volantis/


